spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  application: 
    name: sunnly-microservicecloud-config-dev
---
spring:
  profiles: test
  application: 
    name: sunnly-microservicecloud-config-test